name: Build Development
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.9.0]
        
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm Install
      run: |
        npm install
        
    - name: Set Environment
      run: |
        cp dev.env .env
       
    - name: run build
      run: |
        CI=false npm run build
        ls
        ls build/
        
    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://<bucket-name> --delete
        
    - name: invalidate cloudfront
      run: |
        AWS_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id 	<cf-distribution-id> --paths '/*' --query 'Invalidation.Id' --output text)
        aws cloudfront wait invalidation-completed --distribution-id 	<cf-distribution-id> --id $AWS_INVALIDATION_ID